### PR TITLE
Adding "--sleep-requests 0.5" to prevent 429 errors.

### PR DESCRIPTION
**Pull request by LSchallot**
This should complete #59

### CODE REVIEW

**Comment by TheFrenchGhosty** [comment]
Great, however this is something I forgot to add to the issue, but I want it set to 1, if you're not able to do it, I will do it tomorrow.

**Comment by TheFrenchGhosty** [comment]
Amazing! Thanks a lot!

**Comment by github-account1111** [comment]
Why 1? Also maybe [this](https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection/blob/master/docs/Details.md) needs updated.

**Comment by TheFrenchGhosty** [comment]
@github-account1111 1 is "safer" and good enough

**Pull request merged**
