### PR TITLE
Modified & enhanced docs wrt paths

### PR DESCRIPTION
**Pull request by 93-infinity**
Original without modifying your docs: https://pad.snopyta.org/ykmEOXasS5GiaEF1f9eymw

Pull request because:

Issue 1 - replace references to long paths in cygwin/wsl subsections

Aside from the WSL-specific instructions, most of the stuff relating to long paths (background, workarounds, video player apps) are not specific to WSL, and equally apply to the Cygwin-Git-Bash section. I've stripped all mentions of long paths from the new WSL & existing Cygwin-Git-Bash sections. This keeps both parts purely install-related. A common section redirecting to docs/LongPaths is added to them both, with a cliffhanger (videos won't be playable) to entice users to actually read it

Issue 2 - Modify README.md
- remove your references to path length limit
- details the fate of the Windows version (mainly your text, use some verbiage from the Cygwin-Git-Bash section)
- WSL is not the only thing that bypasses path length limits, removed this parts - is it? check (I did not check if cygwin does)
- effect of path length on playback of videos - removed
- Add the same common section redirecting to docs/LongPaths as wsl/cygwin install instructions, with same cliffhanger (videos won't be playable) to entice users to actually read it

Issue 3 - Create docs/LongPaths.md
- stuff everything about long paths here, to avoid cluttering up README.md

### CODE REVIEW

**Comment by 93-infinity** [comment]
@TheFrenchGhosty can you change the following (don't know how to without submitting new PR sorry)

> However files and folders created by programs that support "long paths" will be impossible to manipulate. They are valid files, but will not be able to be opened, copied, moved, renamed, or deleted."

to

> However files and folders created by programs that support "long paths" will be difficult to manipulate with most programs. They are valid files, but will not be able to be easily opened, copied, moved, renamed, or deleted, without special tools.

reason: they are difficult, not impossible, to manipulate. Also:

> Windows and other programs will not let you manipulate files with long paths. Overcome this by manipulating files inside WSL using commandline Linux tools (cp, mv, rm). Alternatively, use a file manager like mc (Midnight Commander). 

to

> Windows and most programs will not let you easily manipulate files with long paths. Overcome this by manipulating files inside WSL. Use built-in Linux commandline tools like cp (to copy), mv (to move), and rm (to delete), or a file manager like mc (Midnight Commander). 

reason: same as above + explain [cp+mv+rm] + fix sentence structure to remove implication mc is not a linux program

**Comment by 93-infinity** [comment]
Outstanding issue, if cygwin doesn't support long paths (what's the point of using it, then), then simply add note in readme in the future to specify only WSL's support.

**Comment by 93-infinity** [comment]
Still has some typos

**Review by TheFrenchGhosty — APPROVED** [review]

**Comment by TheFrenchGhosty** [comment]
Sorry that it took me so long to get to it.

Thanks a lot for this really detailed documentation enhancement! This will definitely help windows users.

**Pull request merged**
