### PR TITLE
Reformatted All Scripts

### PR DESCRIPTION
**Pull request by Player-5**
All scripts are now split across multiple lines instead of a single one.
This should improve readability, and make future work easier.

### CODE REVIEW

**Comment by TheFrenchGhosty** [comment]
I will review it later, thanks a lot for taking the time to do it.

Closes #83

**Comment by Player-5** [comment]
is it later yet?

**Comment by madprogramer** [comment]
(bump)

**Comment by Degura** [comment]
(bump)

**Comment by TheFrenchGhosty** [comment]
This is outdated and is honestly impossible to audit. I have to do it myself.

Sorry.

**Pull request closed without merging**
